name: Imagebuilder

on:
  workflow_dispatch:
    inputs:
      k8stag:
        description: 'Kubernetes tag to build from'
        type: text
        required: true

permissions:
  packages: write

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
    env:
      JOB_NAME: "nodeimage-${{ inputs.k8stag }}"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Check out kubernetes
        run: |
          gopath=$(go env GOPATH)
          git clone --branch ${{ inputs.k8stag }} --depth 1 https://github.com/kubernetes/kubernetes.git ${gopath}/src/k8s.io/kubernetes

      - name: Install kind
        run: sudo make install INSTALL_DIR=/usr/local/bin

      - name: Build image
        run: |
          gopath=$(go env GOPATH)
          imagetag=$(date +v%Y%m%d)-$(git describe --always --dirty)
          registry=ghcr.io/fougner
          make REGISTRY=${registry} TAG=${imagetag} -C images/base/ quick
          kind build node-image --base-image ${registry}/base:${imagetag} --image ghcr.io/fougner/node:${{ inputs.k8stag }}

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Enable ipv4 and ipv6 forwarding
        run: |
          sudo sysctl -w net.ipv6.conf.all.forwarding=1
          sudo sysctl -w net.ipv4.ip_forward=1

      - name: Create multi node cluster
        run: |
          /usr/local/bin/kind create cluster -v7 --wait 1m --retain --image ghcr.io/fougner/node:${{ inputs.k8stag }}

      - name: Get Cluster status
        run: |
          # wait network is ready
          kubectl wait --for=condition=ready pods --namespace=kube-system -l k8s-app=kube-dns
          kubectl get nodes -o wide
          kubectl get pods -A

      - name: Load docker image
        run: |
          docker pull busybox
          /usr/local/bin/kind load docker-image busybox

      - name: Export logs
        if: always()
        run: |
          mkdir -p /tmp/kind/logs
          /usr/local/bin/kind export logs /tmp/kind/logs
          sudo chown -R $USER:$USER /tmp/kind/logs

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
        with:
          name: kind-logs-${{ env.JOB_NAME }}-${{ github.run_id }}
          path: /tmp/kind/logs

      - name: Delete cluster
        run: /usr/local/bin/kind delete cluster

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish image
        run: docker push ghcr.io/fougner/node:${{ inputs.k8stag }}